name: Build imxInsights CLI app

# https://github.com/marketplace/actions/trigger-external-workflow


on:
  workflow_call:

  push:
    branches: [ "master", "refactor*", "feature-*"]

  pull_request:
    branches: [ "master", "refactor*", "feature-*"]

  repository_dispatch:
    types: [build_cli_apps]

permissions:
  contents: write

jobs:

  bake-cli-apps:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flit
          flit install --deps develop

#      - name: Bump version and commit changes
#        if: ${{ github.event_name == 'workflow_call' }}
#        run: |
#          git config --global user.name 'Your Name'
#          git config --global user.email 'hazedd@users.noreply.github.com'
#          make bumpversion-build
#          git commit -am "Bump version [skip ci]"  # Skip CI to avoid recursive runs
#          git push

      - name: Bake cli apps with PyInstaller
        shell: pwsh
        run: |
          $VERSION = python -c "import re; print(re.search('__version__ = `"(.*)`"', open('imxInsightsCli/imxDiffCli/__init__.py').read()).group(1))"
          Write-Host "Building version $VERSION..."
          python -m PyInstaller imxInsightsCli/imxDiffCli/imx_diff.py --onefile --add-data "${{ env.pythonLocation }}/Lib/site-packages/imxInsights/custom_puic_config.yaml:imxInsights/." --icon=imxInsightsCli/imxDiffCli/diff.ico --name ImxDiff-$VERSION

      - name: Create IMX diff artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_cli_diff_app
          path: |
            ${{ github.workspace }}/dist/imx_diff.exe

      # todo: create release and add artifact
