name: Build imxInsights CLI apps

# https://github.com/marketplace/actions/trigger-external-workflow

on:
  repository_dispatch:
    types: [build_cli_apps]

jobs:
  update-docs:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

#      - name: Install dependencies
#        run: |
#          python -m pip install --upgrade pip
#          pip install flit
#          flit install --deps develop

#      # todo: setup python, install dependencies
#
#      - name: Bake cli app with PyInstaller
#        run: |
#          make build-cli-app
#
#      - name: Copy cli yaml settings to dist folder
#        run: |
#          cp -r ${{ github.workspace }}/cli/app_settings.yaml ${{ github.workspace }}/dist/
#
#      - uses: actions/upload-artifact@v3
#        with:
#          name: windows_cli_diff_app
#          path: |
#            ${{ github.workspace }}/dist/imx_to_excel.exe
#            ${{ github.workspace }}/dist/app_settings.yaml
