name: Build imxInsights CLI apps

# https://github.com/marketplace/actions/trigger-external-workflow

on:
  workflow_call:

  push:
    branches: [ "master", "refactor*", "feature-*"]

  pull_request:
    branches: [ "master", "refactor*", "feature-*"]

  repository_dispatch:
    types: [build_cli_apps]

jobs:

  bake-cli-apps:
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flit
          flit install --deps develop

      - name: Bake cli apps with PyInstaller
        run: |
          python -m PyInstaller imxInsightsCli/imxDiffCli/imx_diff.py --onefile --add-data "${{ env.pythonLocation }}/Lib/site-packages/imxInsights/custom_puic_config.yaml:imxInsights/." --icon=imxInsightsCli/imxDiffCli/diff.ico

#      - name: Copy imxInsights yaml settings to IMX diff dist folder
#        run: |
#          cp -r ${{ github.workspace }}/imxInsightsCli/imxDiffCli/app_settings.yaml ${{ github.workspace }}/dist/

      - name: Create IMX diff artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows_cli_diff_app
          path: |
            ${{ github.workspace }}/dist/imx_to_excel.exe
