name: Repository Dispatch

on:
  repository_dispatch:
    types: [build_cli_app]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Triggered Workflow
        run: echo "This workflow was triggered using repository_dispatch."."
